### ISSUE TITLE
`ssh.coordinates` value is incorrect for v201905

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/SalishSeaNowcast#152]
In `nowcast.yaml`:
```yaml
ssh:
  ...
  # Coordinates file to get lats/lons from
  coordinates: /SalishSeaCast/grid/coordinates_seagrid_SalishSea2.nc
  ...
```
should be:
```yaml
ssh:
  ...
  # Coordinates file to get lats/lons from
  coordinates: /SalishSeaCast/grid/coordinates_seagrid_SalishSea201702.nc
  ...
```
